import React, { useState, useMemo, useCallback } from 'react';
import { useGym } from '../context/GymContext';
import { useFilteredMembers } from '../hooks/useFilteredMembers';
import { useAuth } from '../hooks/useAuth';
import { usePayments } from '../hooks/usePayments';
import { Modal } from '../components/common/Modal';
import { Badge } from '../components/common/Badge';
import { Phone, Award, Users, DollarSign, User } from 'lucide-react';
import type { Coach } from '../types';
import { formatCurrency, getPlanName } from '../utils/helpers';

export const Coaches: React.FC = () => {
  const { coaches, plans } = useGym();
  const { filterCoachesByAccess } = useAuth();
  const { members } = useFilteredMembers();
  const { payments } = usePayments();
  const [selectedCoach, setSelectedCoach] = useState<Coach | null>(null);

  // Filter coaches by gender then compute member counts
  const coachesWithCounts = useMemo(() => {
    const filtered = filterCoachesByAccess(coaches);
    return filtered.map(coach => {
      const assignedCount = members.filter(m => m.coachId === coach.id).length;
      return {
        ...coach,
        assignedMembersCount: assignedCount
      };
    });
  }, [coaches, members, filterCoachesByAccess]);

  // Selected coach with client-computed count
  const selectedCoachWithCount = useMemo(() => {
    if (!selectedCoach) return null;
    return coachesWithCounts.find(c => c.id === selectedCoach.id) || selectedCoach;
  }, [selectedCoach, coachesWithCounts]);

  // Get members assigned to selected coach
  const coachMembers = useMemo(() => {
    return selectedCoach
      ? members.filter((m) => m.coachId === selectedCoach.id)
      : [];
  }, [selectedCoach, members]);

  // Memoized payments map by memberId for O(1) lookups
  const memberPaidMap = useMemo(() => {
    const map: Record<string, number> = {};
    payments.forEach(p => {
      if (p.status === 'paid') {
        map[p.memberId] = (map[p.memberId] || 0) + Number(p.amount);
      }
    });
    return map;
  }, [payments]);

  const getMemberPaidAmount = useCallback((memberId: string) => {
    return memberPaidMap[memberId] || 0;
  }, [memberPaidMap]);

  // Compute total revenue generated by coach's members
  const coachTotalRevenue = useMemo(() => {
    return coachMembers.reduce((sum, m) => sum + getMemberPaidAmount(m.id), 0);
  }, [coachMembers, getMemberPaidAmount]);

  return (
    <div className="space-y-6 animate-fade-in pb-10">
      {/* Header */}
      <div>
        <h2 className="text-xl font-black text-slate-800 dark:text-slate-100 tracking-tight">دليل المدربين</h2>
        <p className="text-sm text-slate-500 dark:text-slate-400 font-medium mt-0.5">
          عرض ملفات فريق المدربين الشخصيين، ومتابعة العملاء المسندين لكل مدرب والمدفوعات الخاصة بهم.
        </p>
      </div>

      {/* Grid of Coaches */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
        {coachesWithCounts.map((coach) => (
          <div
            key={coach.id}
            onClick={() => setSelectedCoach(coach)}
            className="bg-white dark:bg-slate-900 border border-slate-100 dark:border-slate-800 rounded-2xl overflow-hidden shadow-xs hover:shadow-lg hover:border-emerald-300 dark:hover:border-emerald-500 transition-all duration-300 flex flex-col justify-between cursor-pointer group"
          >
            {/* Header info / Avatar */}
            <div>
              <div className="relative h-48 w-full bg-slate-900 overflow-hidden">
                <img
                  src={coach.avatar || `https://ui-avatars.com/api/?name=${encodeURIComponent(coach.name)}&background=1e293b&color=fff`}
                  alt={coach.name}
                  className="w-full h-full object-cover opacity-90 group-hover:scale-105 transition-transform duration-500"
                />
                <div className="absolute top-3 right-3">
                  <span className="inline-flex items-center gap-1 px-2.5 py-1 rounded-lg bg-slate-950/80 backdrop-blur-md text-[10px] font-extrabold text-emerald-400 border border-slate-800">
                    <Award className="h-3 w-3" />
                    <span>مدرب</span>
                  </span>
                </div>
              </div>

              <div className="p-5 space-y-3">
                <div>
                  <h3 className="text-base font-black text-slate-800 dark:text-slate-100 tracking-tight group-hover:text-emerald-600 dark:group-hover:text-emerald-400 transition-colors">
                    {coach.name}
                  </h3>
                  <p className="text-xs font-bold text-slate-400 dark:text-slate-500 mt-1 uppercase tracking-wider">
                    {coach.specialty}
                  </p>
                </div>

                <div className="flex items-center gap-2 text-xs font-bold text-slate-600 dark:text-slate-300 bg-slate-50 dark:bg-slate-800/50 border border-slate-100 dark:border-slate-700 p-2.5 rounded-xl">
                  <Users className="h-4 w-4 text-emerald-500" />
                  <span>{coach.assignedMembersCount} عميل مسند</span>
                </div>
              </div>
            </div>

            {/* Contact Information Footer */}
            <div className="px-5 pb-5 pt-3 border-t border-slate-50 dark:border-slate-800 space-y-2 text-xs font-semibold text-slate-500 dark:text-slate-400">
              <div className="flex items-center gap-2">
                <Phone className="h-4 w-4 text-slate-400 dark:text-slate-500 flex-shrink-0" />
                <span>{coach.phone}</span>
              </div>

              <button
                onClick={(e) => {
                  e.stopPropagation();
                  setSelectedCoach(coach);
                }}
                className="w-full mt-3 py-2.5 rounded-xl bg-slate-50 dark:bg-slate-800 group-hover:bg-emerald-500 dark:group-hover:bg-emerald-500 group-hover:text-slate-950 text-slate-700 dark:text-slate-300 font-extrabold text-center transition-all cursor-pointer border border-transparent"
              >
                عرض الملف والعملاء
              </button>
            </div>
          </div>
        ))}
      </div>

      {/* Coach Detail Profile Modal */}
      {selectedCoachWithCount && (
        <Modal
          isOpen={!!selectedCoachWithCount}
          onClose={() => setSelectedCoach(null)}
          title={`الملف الشخصي للمدرب: ${selectedCoachWithCount.name}`}
          size="lg"
        >
          <div className="space-y-6">
            {/* Coach Card Info */}
            <div className="flex flex-col sm:flex-row gap-5 items-center bg-slate-50 dark:bg-slate-800/50 border border-slate-100 dark:border-slate-800 rounded-2xl p-5">
              <img
                src={selectedCoachWithCount.avatar || `https://ui-avatars.com/api/?name=${encodeURIComponent(selectedCoachWithCount.name)}&background=1e293b&color=fff`}
                alt={selectedCoachWithCount.name}
                className="w-20 h-20 rounded-full object-cover border-2 border-emerald-500 shadow-sm"
              />
              <div className="text-center sm:text-right space-y-1">
                <h4 className="text-lg font-black text-slate-800 dark:text-slate-100">{selectedCoachWithCount.name}</h4>
                <p className="text-xs font-extrabold text-emerald-600 dark:text-emerald-400 uppercase tracking-wider">
                  {selectedCoachWithCount.specialty}
                </p>
                <div className="flex items-center justify-center sm:justify-start gap-2 text-xs text-slate-500 dark:text-slate-400 font-semibold mt-1">
                  <Phone className="h-3.5 w-3.5" />
                  <span>{selectedCoachWithCount.phone}</span>
                </div>
              </div>
            </div>

            {/* Quick Stats Grid */}
            <div className="grid grid-cols-2 gap-4">
              <div className="bg-white dark:bg-slate-900 border border-slate-100 dark:border-slate-800 p-4 rounded-xl shadow-2xs flex items-center gap-3">
                <div className="p-2.5 bg-emerald-50 dark:bg-emerald-950/50 text-emerald-600 dark:text-emerald-400 rounded-xl">
                  <Users className="h-5 w-5" />
                </div>
                <div>
                  <p className="text-[10px] font-bold text-slate-400 dark:text-slate-500 uppercase">العملاء المشتركون</p>
                  <p className="text-lg font-black text-slate-800 dark:text-slate-100">{coachMembers.length}</p>
                </div>
              </div>

              <div className="bg-white dark:bg-slate-900 border border-slate-100 dark:border-slate-800 p-4 rounded-xl shadow-2xs flex items-center gap-3">
                <div className="p-2.5 bg-amber-50 dark:bg-amber-950/50 text-amber-600 dark:text-amber-400 rounded-xl">
                  <DollarSign className="h-5 w-5" />
                </div>
                <div>
                  <p className="text-[10px] font-bold text-slate-400 dark:text-slate-500 uppercase">مجموع الإيرادات</p>
                  <p className="text-lg font-black text-slate-800 dark:text-slate-100">{formatCurrency(coachTotalRevenue, 0)} شيكل</p>
                </div>
              </div>
            </div>

            {/* Members List Section */}
            <div className="space-y-3">
              <h5 className="text-xs font-black text-slate-700 dark:text-slate-300 uppercase tracking-wider">العملاء المسندون للمدرب</h5>
              
              {coachMembers.length === 0 ? (
                <div className="text-center py-8 border-2 border-dashed border-slate-100 dark:border-slate-800 rounded-2xl">
                  <User className="h-8 w-8 text-slate-300 dark:text-slate-600 mx-auto mb-2" />
                  <p className="text-sm font-semibold text-slate-400 dark:text-slate-500">لا يوجد عملاء مسندين حالياً</p>
                </div>
              ) : (
                <div className="divide-y divide-slate-150 dark:divide-slate-800 border border-slate-150 dark:border-slate-800 rounded-2xl overflow-hidden bg-white dark:bg-slate-900 max-h-[250px] overflow-y-auto">
                  {coachMembers.map((member) => {
                    const paidAmount = getMemberPaidAmount(member.id);
                    return (
                      <div key={member.id} className="flex justify-between items-center p-3.5 hover:bg-slate-50 dark:hover:bg-slate-800/50 transition-colors">
                        <div className="flex items-center gap-3">
                          <div className="w-8 h-8 rounded-full bg-slate-100 dark:bg-slate-800 flex items-center justify-center font-bold text-slate-650 dark:text-slate-300 text-sm">
                            {member.name.charAt(0)}
                          </div>
                          <div>
                            <p className="text-xs font-black text-slate-800 dark:text-slate-200">{member.name}</p>
                            <p className="text-[10px] text-slate-400 dark:text-slate-500 font-semibold mt-0.5">{getPlanName(member.planId, plans)}</p>
                          </div>
                        </div>
                        
                        <div className="flex items-center gap-4">
                          <div className="text-left">
                            <p className="text-xs font-black text-slate-700 dark:text-slate-300">{formatCurrency(paidAmount, 0)} شيكل</p>
                            <p className="text-[9px] text-slate-400 dark:text-slate-500 font-semibold">إجمالي الدفعات</p>
                          </div>
                          <Badge type={member.status} />
                        </div>
                      </div>
                    );
                  })}
                </div>
              )}
            </div>
          </div>
        </Modal>
      )}
    </div>
  );
};
